---
abstract: 'Perl extension for scrubbing/sanitizing HTML'
author:
  - 'Ruslan Zakirov <Ruslan.Zakirov@gmail.com>'
  - 'Nigel Metheringham <nigelm@cpan.org>'
  - 'D. H. <podmaster@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  File::Temp: '0'
  Pod::Coverage::TrustPod: '0'
  Test: '0'
  Test::CPAN::Meta: '0'
  Test::Differences: '0'
  Test::EOL: '0'
  Test::Kwalitee: '1.21'
  Test::Memory::Cycle: '0'
  Test::More: '0.88'
  Test::NoTabs: '0'
  Test::PAUSE::Permissions: '0'
  Test::Pod: '1.41'
  Test::Pod::Coverage: '1.08'
  utf8: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.007, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: HTML-Scrubber
no_index:
  directory:
    - eg
    - examples
    - inc
    - share
    - t
    - xt
provides:
  HTML::Scrubber:
    file: lib/HTML/Scrubber.pm
    version: '0.16'
requires:
  HTML::Entities: '0'
  HTML::Parser: '3.47'
  List::Util: '0'
  Scalar::Util: '0'
  perl: '5.008'
  strict: '0'
  warnings: '0'
resources:
  homepage: https://github.com/nigelm/html-scrubber
  repository: https://github.com/nigelm/html-scrubber.git
version: '0.16'
x_Dist_Zilla:
  perl:
    version: '5.024000'
  plugins:
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: AutoPrereqs
      version: '6.007'
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: test
          type: requires
      name: TestRequires
      version: '6.007'
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: NextRelease
      version: '6.007'
    -
      class: Dist::Zilla::Plugin::Git::Check
      config:
        Dist::Zilla::Plugin::Git::Check:
          untracked_files: die
        Dist::Zilla::Role::Git::DirtyFiles:
          allow_dirty:
            - Changes
            - README.md
            - dist.ini
          allow_dirty_match: []
          changelog: Changes
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@Git/Check'
      version: '2.039'
    -
      class: Dist::Zilla::Plugin::Git::Commit
      config:
        Dist::Zilla::Plugin::Git::Commit:
          add_files_in: []
          commit_msg: v%v%n%n%c
        Dist::Zilla::Role::Git::DirtyFiles:
          allow_dirty:
            - Changes
            - README.md
            - dist.ini
          allow_dirty_match: []
          changelog: Changes
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
        Dist::Zilla::Role::Git::StringFormatter:
          time_zone: local
      name: '@Git/Commit'
      version: '2.039'
    -
      class: Dist::Zilla::Plugin::Git::Tag
      config:
        Dist::Zilla::Plugin::Git::Tag:
          branch: ~
          changelog: Changes
          signed: 0
          tag: release/0.16
          tag_format: release/%v
          tag_message: '%v'
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
        Dist::Zilla::Role::Git::StringFormatter:
          time_zone: local
      name: '@Git/Tag'
      version: '2.039'
    -
      class: Dist::Zilla::Plugin::Git::Push
      config:
        Dist::Zilla::Plugin::Git::Push:
          push_to:
            - origin
          remotes_must_exist: 1
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@Git/Push'
      version: '2.039'
    -
      class: Dist::Zilla::Plugin::Git::GatherDir
      config:
        Dist::Zilla::Plugin::GatherDir:
          exclude_filename: []
          exclude_match: []
          follow_symlinks: 0
          include_dotfiles: 0
          prefix: ''
          prune_directory: []
          root: .
        Dist::Zilla::Plugin::Git::GatherDir:
          include_untracked: 0
      name: Git::GatherDir
      version: '2.039'
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      config:
        Dist::Zilla::Plugin::Git::NextVersion:
          first_version: '0.001'
          version_by_branch: 0
          version_regexp: (?^u:^release/(\d+.\d+)$)
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: Git::NextVersion
      version: '2.039'
    -
      class: Dist::Zilla::Plugin::Git::CheckFor::CorrectBranch
      config:
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: Git::CheckFor::CorrectBranch
      version: '0.013'
    -
      class: Dist::Zilla::Plugin::Git::Remote::Check
      name: Git::Remote::Check
      version: 0.1.2
    -
      class: Dist::Zilla::Plugin::Git::Contributors
      config:
        Dist::Zilla::Plugin::Git::Contributors:
          'git --version': 2.13.0
          include_authors: 0
          include_releaser: 1
          order_by: name
          paths: []
      name: Git::Contributors
      version: '0.029'
    -
      class: Dist::Zilla::Plugin::Git::CommitBuild
      config:
        Dist::Zilla::Plugin::Git::CommitBuild:
          branch: ''
          build_root: ~
          message: 'Build results of %h (on %b)'
          multiple_inheritance: 0
          release_branch: cpan
          release_message: 'Build results of %h (on %b)'
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: Git::CommitBuild
      version: '2.039'
    -
      class: Dist::Zilla::Plugin::Test::Perl::Critic
      name: Test::Perl::Critic
      version: '3.000'
    -
      class: Dist::Zilla::Plugin::MetaTests
      name: MetaTests
      version: '6.007'
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: PodCoverageTests
      version: '6.007'
    -
      class: Dist::Zilla::Plugin::OurPkgVersion
      name: OurPkgVersion
      version: '0.10'
    -
      class: Dist::Zilla::Plugin::Test::Kwalitee
      config:
        Dist::Zilla::Plugin::Test::Kwalitee:
          filename: xt/release/kwalitee.t
          skiptest: []
      name: Test::Kwalitee
      version: '2.12'
    -
      class: Dist::Zilla::Plugin::Test::EOL
      config:
        Dist::Zilla::Plugin::Test::EOL:
          filename: xt/author/eol.t
          finder:
            - ':ExecFiles'
            - ':InstallModules'
            - ':TestFiles'
          trailing_whitespace: 1
      name: Test::EOL
      version: '0.19'
    -
      class: Dist::Zilla::Plugin::Test::PAUSE::Permissions
      name: Test::PAUSE::Permissions
      version: '0.003'
    -
      class: Dist::Zilla::Plugin::Test::NoTabs
      config:
        Dist::Zilla::Plugin::Test::NoTabs:
          filename: xt/author/no-tabs.t
          finder:
            - ':InstallModules'
            - ':ExecFiles'
            - ':TestFiles'
      name: Test::NoTabs
      version: '0.15'
    -
      class: Dist::Zilla::Plugin::GithubMeta
      name: GithubMeta
      version: '0.54'
    -
      class: Dist::Zilla::Plugin::PodWeaver
      config:
        Dist::Zilla::Plugin::PodWeaver:
          finder:
            - ':InstallModules'
            - ':ExecFiles'
          plugins:
            -
              class: Pod::Weaver::Plugin::WikiDoc
              name: -WikiDoc
              version: '0.093004'
            -
              class: Pod::Weaver::Plugin::EnsurePod5
              name: '@CorePrep/EnsurePod5'
              version: '4.014'
            -
              class: Pod::Weaver::Plugin::H1Nester
              name: '@CorePrep/H1Nester'
              version: '4.014'
            -
              class: Pod::Weaver::Plugin::SingleEncoding
              name: '@Default/SingleEncoding'
              version: '4.014'
            -
              class: Pod::Weaver::Section::Name
              name: '@Default/Name'
              version: '4.014'
            -
              class: Pod::Weaver::Section::Version
              name: '@Default/Version'
              version: '4.014'
            -
              class: Pod::Weaver::Section::Region
              name: '@Default/prelude'
              version: '4.014'
            -
              class: Pod::Weaver::Section::Generic
              name: SYNOPSIS
              version: '4.014'
            -
              class: Pod::Weaver::Section::Generic
              name: DESCRIPTION
              version: '4.014'
            -
              class: Pod::Weaver::Section::Generic
              name: OVERVIEW
              version: '4.014'
            -
              class: Pod::Weaver::Section::Collect
              name: ATTRIBUTES
              version: '4.014'
            -
              class: Pod::Weaver::Section::Collect
              name: METHODS
              version: '4.014'
            -
              class: Pod::Weaver::Section::Collect
              name: FUNCTIONS
              version: '4.014'
            -
              class: Pod::Weaver::Section::Leftovers
              name: '@Default/Leftovers'
              version: '4.014'
            -
              class: Pod::Weaver::Section::Region
              name: '@Default/postlude'
              version: '4.014'
            -
              class: Pod::Weaver::Section::Authors
              name: '@Default/Authors'
              version: '4.014'
            -
              class: Pod::Weaver::Section::Legal
              name: '@Default/Legal'
              version: '4.014'
            -
              class: Pod::Weaver::Section::Support
              name: Support
              version: '1.007'
            -
              class: Pod::Weaver::Section::Contributors
              name: Contributors
              version: '0.009'
            -
              class: Pod::Weaver::Plugin::Transformer
              name: -Transformer
              version: '4.014'
      name: PodWeaver
      version: '4.008'
    -
      class: Dist::Zilla::Plugin::CheckChangeLog
      name: CheckChangeLog
      version: '0.02'
    -
      class: Dist::Zilla::Plugin::Authority
      name: Authority
      version: '1.009'
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Starter/PruneCruft'
      version: '6.007'
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Starter/ManifestSkip'
      version: '6.007'
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@Starter/MetaConfig'
      version: '6.007'
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      config:
        Dist::Zilla::Plugin::MetaProvides::Package:
          finder_objects:
            -
              class: Dist::Zilla::Plugin::FinderCode
              name: '@Starter/MetaProvides::Package/AUTOVIV/:InstallModulesPM'
              version: '6.007'
          include_underscores: 0
        Dist::Zilla::Role::MetaProvider::Provider:
          $Dist::Zilla::Role::MetaProvider::Provider::VERSION: '2.002003'
          inherit_missing: '1'
          inherit_version: '1'
          meta_noindex: '1'
        Dist::Zilla::Role::ModuleMetadata:
          Module::Metadata: '1.000031'
          version: '0.004'
      name: '@Starter/MetaProvides::Package'
      version: '2.004002'
    -
      class: Dist::Zilla::Plugin::MetaNoIndex
      name: '@Starter/MetaNoIndex'
      version: '6.007'
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Starter/MetaYAML'
      version: '6.007'
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@Starter/MetaJSON'
      version: '6.007'
    -
      class: Dist::Zilla::Plugin::License
      name: '@Starter/License'
      version: '6.007'
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      config:
        Dist::Zilla::Role::FileWatcher:
          version: '0.006'
      name: '@Starter/ReadmeAnyFromPod'
      version: '0.161170'
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@Starter/ExecDir'
      version: '6.007'
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@Starter/ShareDir'
      version: '6.007'
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@Starter/PodSyntaxTests'
      version: '6.007'
    -
      class: Dist::Zilla::Plugin::Test::ReportPrereqs
      name: '@Starter/Test::ReportPrereqs'
      version: '0.025'
    -
      class: Dist::Zilla::Plugin::Test::Compile
      config:
        Dist::Zilla::Plugin::Test::Compile:
          bail_out_on_fail: '0'
          fail_on_warning: author
          fake_home: 0
          filename: xt/author/00-compile.t
          module_finder:
            - ':InstallModules'
          needs_display: 0
          phase: develop
          script_finder:
            - ':PerlExecFiles'
          skips: []
      name: '@Starter/Test::Compile'
      version: '2.054'
    -
      class: Dist::Zilla::Plugin::MakeMaker
      config:
        Dist::Zilla::Role::TestRunner:
          default_jobs: 1
      name: '@Starter/MakeMaker'
      version: '6.007'
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Starter/Manifest'
      version: '6.007'
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Starter/TestRelease'
      version: '6.007'
    -
      class: Dist::Zilla::Plugin::RunExtraTests
      config:
        Dist::Zilla::Role::TestRunner:
          default_jobs: 1
      name: '@Starter/RunExtraTests'
      version: '0.029'
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@Starter/ConfirmRelease'
      version: '6.007'
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Starter/UploadToCPAN'
      version: '6.007'
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      config:
        Dist::Zilla::Role::FileWatcher:
          version: '0.006'
      name: Markdown_Readme
      version: '0.161170'
    -
      class: Dist::Zilla::Plugin::Meta::Contributors
      name: Meta::Contributors
      version: '0.003'
    -
      class: Dist::Zilla::Plugin::GitHubREADME::Badge
      name: GitHubREADME::Badge
      version: '0.20'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: '6.007'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: '6.007'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: '6.007'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExtraTestFiles'
      version: '6.007'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: '6.007'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':PerlExecFiles'
      version: '6.007'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: '6.007'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: '6.007'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':AllFiles'
      version: '6.007'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':NoFiles'
      version: '6.007'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: '@Starter/MetaProvides::Package/AUTOVIV/:InstallModulesPM'
      version: '6.007'
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: '1'
    version: '6.007'
x_authority: cpan:NIGELM
x_contributors:
  - 'Andrei Vereha <avereha@gmail.com>'
  - 'Lee Johnson <lee@givengain.ch>'
  - 'Michael Caron <michael.r.caron@gmail.com>'
  - 'Michael Caron <mrcaron@users.noreply.github.com>'
  - 'Nigel Metheringham <nm9762github@muesli.org.uk>'
  - 'Paul Cochrane <paul@liekut.de>'
  - 'Ruslan Zakirov <ruz@bestpractical.com>'
  - 'Sergey Romanov <complefor@rambler.ru>'
  - 'vagrant <vagrant@precise64.(none)>'
x_serialization_backend: 'YAML::Tiny version 1.69'
